export const VISITOR_LIST_REQUEST = "VISITOR_LIST_REQUEST";
export const VISITOR_LIST_SUCCESS = "VISITOR_LIST_SUCCESS";
export const VISITOR_LIST_FAIL = "VISITOR_LIST_FAIL";

export const VISITOR_CREATE_REQUEST = "VISITOR_CREATE_REQUEST";
export const VISITOR_CREATE_SUCCESS = "VISITOR_CREATE_SUCCESS";
export const VISITOR_CREATE_FAIL = "VISITOR_CREATE_FAIL";
